spring.application.name=EdTechProject
server.port=${SERVER-PORT}
spring.datasource.url=${POSTGRES-URL}
spring.datasource.username=${POSTGRES-USERNAME}
spring.datasource.password=${POSTGRES-PASSWORD}
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true